name: Create Release and Update Repository

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: ReiwaTech/DalamudPluginRepo/.github/workflows/reusable_create_release.yml@master
    with:
      internal_name: PennyPincher
      solution_name: PennyPincher
      build_configuration: Release
      personal_plugin_repo: ReiwaTech/DalamudPluginRepo
      personal_plugin_repo_branch: master
    secrets: inherit
